to# This is a basic workflow to help you get started with Actions

name: peviitor.ro

# Controls when the workflow will run
on:
    push:
     branches: [ main ]
    pull_request:
     branches: [ main ]
    schedule:
    - cron: '30 18 * * *'

  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Apache JMeter
        uses: rbhadti94/apache-jmeter-action@v0.4.0
        with:
          testFilePath: tecknoworks.jmx
          outputReportsFolder: reports/
          plugins: jpgc-dummy
